name: Publish to Modrinth

on: 
  workflow_dispatch
  
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        run: |
          gradle modrinth
          echo ${{ github.event.sender.login }}
